name: Clang-Tidy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  clang-tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bear clang-tidy

    - name: Download and extract libsodium
      run: |
        URL=$(curl -s https://download.libsodium.org/libsodium/releases/ | grep -oP 'libsodium-\d+\.\d+\.\d+-stable.tar.gz' | tail -n 1)
        wget -O libsodium.tar.gz https://download.libsodium.org/libsodium/releases/$URL
        tar -xzf libsodium.tar.gz
        cd libsodium-*
        ./configure
        make
        sudo make install
        sudo ldconfig

    - name: Generate compile_commands.json
      run: bear -- make all

    - name: Run Clang-Tidy
      run: clang-tidy -p=./ ssoed.c
